workflows:
  ios-release:
    name: iOS Release - Win Daily
    max_build_duration: 120
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: codemagic1
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: ca.windaily.app
      vars:
        APP_ID: 6755403321
        XCODE_PROJECT: ios/Runner.xcodeproj
        BUNDLE_ID: ca.windaily.app
        APPLE_TEAM_ID: 64N2VP6LNJ
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Build iOS
        script: |
          flutter build ipa --release \
            --build-name=1.0.0 \
            --build-number=$BUILD_NUMBER \
            --export-options-plist=ios/ExportOptions.plist
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - hello@windaily.ca
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: true
