-- Add sample data for testing (using existing user from schema)
-- This migration adds sample wins and goals for the existing user

-- Sample Major Goals
INSERT INTO public.major_goals (title, description, user_id, position, is_active, is_archived) 
VALUES 
  ('Health & Fitness', 'Improve overall health and maintain regular exercise routine', '4eb89cf7-90a7-4d1d-a2fc-17e1089c5a37'::uuid, 1, true, false),
  ('Career Growth', 'Advance professional skills and achieve career milestones', '4eb89cf7-90a7-4d1d-a2fc-17e1089c5a37'::uuid, 2, true, false),
  ('Learning & Development', 'Continuous learning and skill development', '4eb89cf7-90a7-4d1d-a2fc-17e1089c5a37'::uuid, 3, true, false)
ON CONFLICT DO NOTHING;

-- Get the goal IDs for sample data (they will be UUIDs generated by the database)
-- We'll use CTEs to get the goal IDs and use them in the daily wins

-- Sample Daily Wins for the past few days
WITH goal_ids AS (
  SELECT id, title FROM public.major_goals 
  WHERE user_id = '4eb89cf7-90a7-4d1d-a2fc-17e1089c5a37'::uuid
  AND is_active = true
  LIMIT 3
),
fitness_goal AS (SELECT id FROM goal_ids WHERE title = 'Health & Fitness'),
career_goal AS (SELECT id FROM goal_ids WHERE title = 'Career Growth'),
learning_goal AS (SELECT id FROM goal_ids WHERE title = 'Learning & Development')

INSERT INTO public.daily_wins (description, goal_id, user_id, win_date, mood_rating, reflection)
SELECT * FROM (
  VALUES 
    ('Completed 30-minute morning workout', (SELECT id FROM fitness_goal), '4eb89cf7-90a7-4d1d-a2fc-17e1089c5a37'::uuid, CURRENT_DATE, 4, 'Felt energized and accomplished starting the day with exercise'),
    ('Finished project proposal ahead of deadline', (SELECT id FROM career_goal), '4eb89cf7-90a7-4d1d-a2fc-17e1089c5a37'::uuid, CURRENT_DATE - INTERVAL '1 day', 5, 'Great feeling to be ahead of schedule and deliver quality work'),
    ('Learned new Flutter widget patterns', (SELECT id FROM learning_goal), '4eb89cf7-90a7-4d1d-a2fc-17e1089c5a37'::uuid, CURRENT_DATE - INTERVAL '2 days', 4, 'These patterns will help me write cleaner code'),
    ('Had a healthy lunch and avoided junk food', (SELECT id FROM fitness_goal), '4eb89cf7-90a7-4d1d-a2fc-17e1089c5a37'::uuid, CURRENT_DATE - INTERVAL '2 days', 3, 'Small wins in nutrition add up over time'),
    ('Completed online course module on system design', (SELECT id FROM learning_goal), '4eb89cf7-90a7-4d1d-a2fc-17e1089c5a37'::uuid, CURRENT_DATE - INTERVAL '3 days', 4, 'Understanding distributed systems better now')
) AS sample_wins(description, goal_id, user_id, win_date, mood_rating, reflection)
WHERE (SELECT id FROM fitness_goal) IS NOT NULL
ON CONFLICT (user_id, goal_id, win_date) DO NOTHING;

-- Sample general wins in the wins table
INSERT INTO public.wins (text, user_id, win_date, category, mood, reflection)
VALUES 
  ('Helped a colleague debug a difficult issue', '4eb89cf7-90a7-4d1d-a2fc-17e1089c5a37'::uuid, CURRENT_DATE, 'work'::public.win_category, 4, 'Collaboration and helping others feels rewarding'),
  ('Read 20 pages of a great book before bed', '4eb89cf7-90a7-4d1d-a2fc-17e1089c5a37'::uuid, CURRENT_DATE - INTERVAL '1 day', 'learning'::public.win_category, 3, 'Building a consistent reading habit'),
  ('Cooked a healthy meal from scratch', '4eb89cf7-90a7-4d1d-a2fc-17e1089c5a37'::uuid, CURRENT_DATE - INTERVAL '1 day', 'self_care'::public.win_category, 4, 'Taking time to nourish my body properly'),
  ('Called a friend I hadn''t spoken to in weeks', '4eb89cf7-90a7-4d1d-a2fc-17e1089c5a37'::uuid, CURRENT_DATE - INTERVAL '2 days', 'relationships'::public.win_category, 5, 'Maintaining friendships is so important for wellbeing'),
  ('Completed a challenging coding problem', '4eb89cf7-90a7-4d1d-a2fc-17e1089c5a37'::uuid, CURRENT_DATE - INTERVAL '3 days', 'learning'::public.win_category, 4, 'Problem-solving skills getting stronger')
ON CONFLICT DO NOTHING;

-- Update the user profile last_seen_at to show recent activity
UPDATE public.user_profiles 
SET last_seen_at = NOW()
WHERE id = '4eb89cf7-90a7-4d1d-a2fc-17e1089c5a37'::uuid;